### PR TITLE
overhauling http query parameters, fixing parsing issues

### LINKED ISSUE #288: Stop using java.net.URI to parse urls, it doesn't work
given a url like `http://foo.bar.com?key=a%3Db`, where `%3D` is a url-encoded `&`, `java.net.URI` incorrectly parses this by first url-decoding and then parsing the query string, so whereas the value of `key` should be `a&b`, it ends up just being `a`.

The solution here is to just write our own parser.  This should be very easy since we just have to split on the first `?` and then split on non-encoded `&` and `=`.

### PR DESCRIPTION
**Pull request by DanSimon**
Fixes #288 .  The new parser correctly handles url encoding inside query parameters.  Also switches from a map to a seq of tuples to handle multiple parameters with the same name (which is allowed) and wrapped the values in a case class with some convenience methods.

I also added a test that shows #279 appears to be invalid.

### CODE REVIEW

**Comment by reeve** [comment]
:+1: 
I assume we don't expect that scanning the seq for headers is expensive enough to make it worth using a multimap or something?

File: colossus/src/main/scala/colossus/protocols/http/Header.scala [hunk 1]
```diff
@@ -176,13 +176,51 @@ object Connection {
...
 }
 
+case class QueryParameters(parameters: Seq[(String, String)]) extends AnyVal{
+
+  def apply(key: String) = singleValue(key).get
+
+  /**
+   * Get the value of a query string parameter when only at most one value is expected
+   **/
+  def singleValue(key: String): Option[String] = parameters.collectFirst{case (k,v) if k == key => v}
```
Comment (amotamed) [inline colossus/src/main/scala/colossus/protocols/http/Header.scala]: how do you feel about getSingle and get (or maybe get and getAll since pulling a single value from a parameter is probably the default case)

**Comment by DanSimon** [comment]
I don't think it's an issue.  It's rare to have more than a few parameters and if we do hit a scenario where requests with many parameters are causing a performance hit during scanning, we'll re-address.

File: colossus/src/main/scala/colossus/protocols/http/Header.scala (hunk 1 above)
Comment (DanSimon) [inline colossus/src/main/scala/colossus/protocols/http/Header.scala]: hmm good point, actually I think `getFirst`and `getAll` would be more appropriate, since that's what they actually do.

Comment (amotamed) [inline colossus/src/main/scala/colossus/protocols/http/Header.scala]: getFirst and getAll FTW!

**Comment by amotamed** [comment]
:+1:
