### PR TITLE
Better exception message format handling

### LINKED ISSUE #594: Create a base trait for some built-in exceptions
There are a bunch of exceptions that are mainly used to indicate an error state has occurred.  `DroppedReplyException`,`RequestTimeoutException`, and `ConnectionLostException` are some examples.  In some (maybe all?) of these cases, the stack trace is completely useless since the exceptions are always generated in the same spot and have no direct relevance to any user code.

We should figure out exactly which exceptions fall into this category and group them under some base type, something like `ColossusRuntimeException`.

### PR DESCRIPTION
**Pull request by benblack86**
Created a `ColossusRuntimeException` trait that is extended by `ServiceClientException`, `ServiceClientExceptions` and `UnhandledRequestException`. I then updated the `RequestFormatter` so it is no longer configurable, but instead will log the name of any `ColossusRuntimeException` and suppress the stack trace. If users want different behavior, then they can write their own `RequestFormatter`. Hopefully this makes the logic a little simpler. Fixes #594

@dkarivalis @DanSimon @aliyakamercan @jlbelmonte @amotamed

### CODE REVIEW

File: colossus/src/main/scala/colossus/service/RequestHandler.scala [hunk 1]
```diff
@@ -58,13 +59,14 @@ abstract class GenRequestHandler[P <: Protocol](val serverContext: ServerContext
...
+
+  private lazy val errorHandler: ErrorHandler[P] = onError orElse unhandledError
 
   def handleFailure(error: ProcessingFailure[Request]): Response = errorHandler(error)
 
   def tagDecorator: TagDecorator[P] = TagDecorator.default[P]
-  def requestLogFormat: Option[RequestFormatter[Request]] =
-    Some(new ConfigurableRequestFormatter[Request](config.errorConfig))
+
+  def requestLogFormat: RequestFormatter[Request] = new StandardRequestFormatter[Request]
```
Comment (dkarivalis) [inline colossus/src/main/scala/colossus/service/RequestHandler.scala]: may be out of scope of this PR .. `RequestFormatter` is a bit ambiguous - possibly refactor the name to `RequestExceptionLogger`?

File: colossus/src/main/scala/colossus/protocols/http/package.scala [hunk 2]
```diff
@@ -40,16 +40,16 @@ package object http {
       ServiceClientFactory.basic("http", () => new StaticHttpClientCodec)
 
     class ServerDefaults {
-      def errorResponse(error: ProcessingFailure[HttpRequest]) = error match {
+      def errorResponse(error: ProcessingFailure[HttpRequest]): HttpResponse = error match {
         case RecoverableError(request, reason) =>
           reason match {
-            case c: UnhandledRequestException => request.notFound(s"Not found")
-            case other                        => request.error(reason.toString)
+            case _: UnhandledRequestException => request.notFound(s"Not found")
```
[the remark this answers is not in the document]
Comment (benblack86) [reply colossus/src/main/scala/colossus/protocols/http/package.scala]: Who needs a linter, when we have @dkarivalis

File: colossus/src/main/scala/colossus/service/RequestHandler.scala (hunk 1 above)
Comment (benblack86) [reply colossus/src/main/scala/colossus/service/RequestHandler.scala]: `RequestExceptionFormatter` sounds good

File: colossus/src/main/scala/colossus/service/ServiceClient.scala [hunk 3]
```diff
@@ -92,7 +93,7 @@ object ClientConfig {
   }
 }
 
-class ServiceClientException(message: String) extends Exception(message)
+class ServiceClientException(message: String) extends Exception(message) with ColossusRuntimeException
```
Comment (amotamed) [inline colossus/src/main/scala/colossus/service/ServiceClient.scala]: this is where we're squashing the stracktrace, we should pass it along here

Comment (benblack86) [reply colossus/src/main/scala/colossus/service/ServiceClient.scala]: Can we get an example of the error that is happening so we can see if the stack trace is helpful, because for all these `ColossusRuntimeException` the stack trace shouldn't be helpful.
