### PR TITLE
Simplify redis API

### LINKED ISSUE #632: Inconsistency between redis and memcache interfaces
More of a question for @DanSimon 

If sending a get request to redis you should generally use `mapTry`:

```
redisClient.get(ByteString(name)).mapTry {
  case Success(value) =>
    // data found
  case Failure(_) =>
    // no data found
}
```

However, memcache returns an option so `map` is sufficient unless you want to handle the case where a incorrect response is sent by memcached.

```
memcacheClient.get(ByteString(name)).map {
  case Some(Value(_, data, _)) =>
    // data found
  case None =>
    // no data found
}
```

Any particular reason for this? Should we make it consistent? Looks like http follows the same style as redis. Which style is the best?

### PR DESCRIPTION
**Pull request by benblack86**
This PR simplifies the Redis API by merging calls that return an option with their counterparts that don't. In other words, returning an option is the default behavior. See https://github.com/tumblr/colossus/issues/632 for more details. Fixes #632 

@DanSimon @aliyakamercan @jlbelmonte @amotamed

### CODE REVIEW

**Comment by benblack86** [comment]
Looks like I need to fix some integration tests.

File: colossus-tests/src/it/scala/colossus/RedisHashITSpec.scala [hunk 1]
```diff
@@ -23,10 +23,10 @@ class RedisHashITSpec extends BaseRedisITSpec{
         _ <- client.hset(delKey, field3, val3)
         x <- client.hdel(delKey, field1, field2)
         y <- client.hget(delKey, field3) //should be unaffected
-        z <- client.hgetOption(delKey, field1) //snould be none, since it was deleted
-      } yield { (x,y,z) }
+        z <- client.hget(delKey, field1) //snould be none, since it was deleted
```
Comment (amotamed) [inline colossus-tests/src/it/scala/colossus/RedisHashITSpec.scala]: let's get that should fixed :)

File: colossus-tests/src/it/scala/colossus/RedisSetITSpec.scala [hunk 2]
```diff
@@ -22,7 +22,7 @@ class RedisSetITSpec extends BaseRedisITSpec {
         (x, y)
       }
 
-      res.futureValue must be ((3, Set(val1, val2, val3)))
+      res.futureValue must be((3, Set(val1, val2, val3)))
```
Comment (amotamed) [inline colossus-tests/src/it/scala/colossus/RedisSetITSpec.scala]: I prefer the space since we're doing that with must, thoughts?

Comment (benblack86) [reply colossus-tests/src/it/scala/colossus/RedisSetITSpec.scala]: This is scalafmt. Since there are brackets involved, I'm guessing it removes the space. Personally, I prefer to use assert(...) instead of must/must be/etc.
