### PR TITLE
A few things in this PR:

### LINKED ISSUE #83: StreamedResponseBuilder for HTTP is broken
Oops.  I broke it.  I am also fixing it, and will have a PR out soon.  The issue is that it is inserting an extra "/r/n" between the HTTP Header and the body.  Good times were had by none.

### PR DESCRIPTION
**Pull request by nsauro**
- Fixed a bug with the HttpServerCodec's StreamingHttpResponseDatReaderBuilder(phew)..this was inserting an extra '/r/n' which was breaking all responses
- Tweaked Controller to reset the 'currentSink' when a PipeClosed/Terminated exception is thrown.
- Fixed a bug with FiniteBytePipe, which was not correctly closing its internal pipe when a size of 0 was given(this was killing incoming streaming http responses with no bodies)
- added a required on FixedBytePipe to disallow negative byte sizes
- Codec: removed type alias for 'Decoded', was just making things unreadable
- StreamingHttpResponse has a new convenience function 'fromValue' which allows the creation of a StreamingResponse from any ByteStringLike
- added a Callback Scalatest Matcher for ease of testing Callbacks
- added more tests surrounding the fixes and additions of the above items
- fixed bug with streaming more than one response out

This has a few things in it, but the big one is the streaming http response fix.
This pr fixes #83, #81, #84, #89

### CODE REVIEW

File: colossus-testkit/src/test/scala/colossus/CallbackMatchersSpec.scala [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+import scala.util.Try
+
+class CallbackMatchersSpec extends WordSpec with MustMatchers{
+
+  import CallbackMatchers._
+
+  "A CallbackMatcher" should {
+
+    "fail to match if a Callback never executes" in {
```
Comment (nsauro) [inline colossus-testkit/src/test/scala/colossus/CallbackMatchersSpec.scala]: @DanSimon ..I think this is a proper test case for testing when a callback never fires....can you verify?

File: colossus/src/main/scala/colossus/controller/Controller.scala [hunk 2]
```diff
@@ -297,8 +300,11 @@ extends ConnectionHandler {
           }
           currentTrigger = Some(trigger)
         }
-        case Failure(reason) => {
-          //todo: what to do here?
+        //TODO: are the following 2 cases really exceptions..seems like they are part of the normal control flow from a controller's POV
```
Comment (nsauro) [inline colossus/src/main/scala/colossus/controller/Controller.scala]: So..I'm not sure how convinced I am of this code.  If the pipe is closed/terminated, we should def reset our sink, as we don't want to push to it..but..there might be more needed here.  Def something to think through.  We might want to have some kind of pluggable behavior here..where if a pipe is closed/terminated while the controller is processing..maybe the controller can take some different actions: ignore, die, etc.  

As I was writing a test for this behavior..is when I started to doubt how "complete" just resetting the sink is.

File: colossus-testkit/src/main/scala/colossus-testkit/CallbackMatchers.scala [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+package testkit
+
+import colossus.service.Callback
+import org.scalatest.matchers.{MatchResult, Matcher}
+
+import scala.util.{Failure, Success}
+
+trait CallbackMatchers {
+
+  class CallbackEvaluateTo[T](f : T => Any) extends Matcher[Callback[T]] {
```
Comment (nsauro) [inline colossus-testkit/src/main/scala/colossus-testkit/CallbackMatchers.scala]: I plan to make a negative matcher, which will match on Failures.  This will be to assert exceptions, etc.

File: colossus/src/main/scala/colossus/protocols/http/HttpServerCodec.scala [hunk 4]
```diff
@@ -88,7 +88,6 @@ object StreamedResponseBuilder extends HttpResponseDataReaderBuilder {
     builder.sizeHint(100)
     appendHeaderBytes(response, builder)
     builder append NEWLINE
-    builder append NEWLINE
```
Comment (nsauro) [inline colossus/src/main/scala/colossus/protocols/http/HttpServerCodec.scala]: This was the heartbreaker...broke streamed http..:).  The tests I wrote in the StreamingHttpresonseParserSpec verify that this is actually working now

File: colossus-tests/src/test/scala/colossus/protocols/http/client/StreamingHttpResponseParserSpec.scala [hunk 5]
```diff
@@ -97,6 +99,45 @@ class StreamingHttpResponseParserSpec extends WordSpec with MustMatchers with Tr
...
+      validateStreamingEncoding(ByteString(""))
+    }
+
+    "decode a response that was encoded by colossus with a body" in {
+      validateStreamingEncoding(ByteString("body bytes!"))
+    }
+
   }
 
+  private def validateStreamingEncoding(body : ByteString){
```
Comment (nsauro) [inline colossus-tests/src/test/scala/colossus/protocols/http/client/StreamingHttpResponseParserSpec.scala]: This test just tests that when we encode a streamed response, we can successfully decode it, which should verify that it is a valid http response.

File: colossus/src/main/scala/colossus/controller/Controller.scala (hunk 2 above)
Comment (DanSimon) [inline colossus/src/main/scala/colossus/controller/Controller.scala]: I'm pretty sure a PipeTerminated exception needs to close the connection, since it means the controller is streaming data into something, and that thing is dead, so the controller has no way to know what to do with the incoming data.  That exception should only be thrown when the situation is basically "Everybody panic!!"  

This does though add evidence that the PipeClosedException should not really be an exception, and just a normal return value.

File: colossus-testkit/src/test/scala/colossus/CallbackMatchersSpec.scala (hunk 1 above)
Comment (DanSimon) [inline colossus-testkit/src/test/scala/colossus/CallbackMatchersSpec.scala]: I think that should do it

File: colossus/src/main/scala/colossus/controller/Controller.scala (hunk 2 above)
Comment (nsauro) [inline colossus/src/main/scala/colossus/controller/Controller.scala]: There is an issue #82 to address those, and that stuff can go into another branch I think.

**Comment by nsauro** [comment]
@DanSimon I will merge this if you approve it.
