### PR TITLE
graceful disconnect allows input stream to finish, fixed pipe bug

### LINKED ISSUE #102: ServiceClient's gracefulDisconnect only takes current writes into consideration
Right now i can start a read from a remote source, and then use gracefulDisconnect to schedule a disconnect for when the read is complete.  Graceful disconnect currently only allows for the current writing operation to finish, and immediately disconnects any read.

This can probably be (easier) to implement with Dan's idea of using a state machine inside of the Controller.

### PR DESCRIPTION
**Pull request by DanSimon**
This fixes #102

### CODE REVIEW

**Comment by nsauro** [comment]
:+1:

File: colossus/src/main/scala/colossus/controller/Controller.scala [hunk 1]
```diff
@@ -190,16 +190,23 @@ extends ConnectionHandler {
...
     //maybe wait instead for the message to finish? probably not
-    currentSink.foreach{_.terminate(new DisconnectingException("Connection is closing"))}
-    currentTrigger.foreach{_.cancel()}
     checkGracefulDisconnect()
   }
 
   private def checkGracefulDisconnect() {
-    if (disconnecting && waitingToSend.size == 0 && currentlyWriting.isEmpty && currentStream.isEmpty) {
+    if (
+      disconnecting &&
```
Comment (nsauro) [inline colossus/src/main/scala/colossus/controller/Controller.scala]: lol.  Yea..we need to do something about all these states :)
