### PR TITLE
Fix scala 2.12 warnings

### LINKED ISSUE #576: Fix scala 2.12 warnings
For example:

screen shot 2017-08-29 at 12 09 05

### PR DESCRIPTION
**Pull request by benblack86**
Fixed scala 2.12 warnings, which were mainly about JavaConversions being deprecated. I then fixed some warnings from intellij. Fixes #576

@DanSimon @aliyakamercan @dxuhuang @nsauro

### CODE REVIEW

File: colossus-metrics/src/main/scala/colossus/metrics/MetricClock.scala [hunk 1]
```diff
@@ -39,29 +37,24 @@ class IntervalAggregator(interval: FiniteDuration,
...
       reporters = reporters + ref
       context.watch(ref)
-    }
 
-    case Terminated(child) => {
+    case Terminated(child) =>
       if (reporters.contains(child)) {
         debug(s"oh no!  We lost a MetricReporter $child. Removing from registered reporters.")
-        reporters.remove(child)
+        reporters = reporters - child
```
Comment (nsauro) [inline colossus-metrics/src/main/scala/colossus/metrics/MetricClock.scala]: glad you found this bug. I was fixing this one in a similar branch addressing these issue :)
